config = {
    "dbms": "MySQL",
    "drivername": "mysql+pymysql",
    "username": "root",
    "host": "localhost",
    "port": "3306",
    "cnx_path": "./cnx.ini",
    "language": "fr",
    "ddl_path": "./ddl.sql",
    "dataset_dir": "./dataset",
    "cheat_sheet_path": "./output/cheat_sheet.md",
    "check_list_path": "./output/check_list.json",
    "source_path": "./ints.ipynb",
    "relational_schema_dir": "./assets/",
    "salt_bound": 100,
    "reformat_sql": True,
    "sqlparse_subs": {
        "lowercase_user_names": (r"\bI\b", lambda m: m[0].lower()),
    },
    "metadata": {
        "version": "0.0.1",
        "repository": "https://github.com/laowantong/ints",
        "license_name": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
        "author_name": "Aristide Grange",
        "author_affiliation": "LCOMS, Université de Lorraine, France",
        "author_contact": "first_name.last_name at univ-lorraine.fr",
        "author_role": "Creation of the exercises",
    },
}
