/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

DROP DATABASE IF EXISTS `ints`;
CREATE DATABASE `ints` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `ints`;

CREATE TABLE `ints` (
  `n` bigint NOT NULL,
  `hash` bigint NULL
) ENGINE=InnoDB;

ALTER TABLE `ints`
  ADD PRIMARY KEY (`n`);

-- FK
